
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x650")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 650,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    900.0,
    650.0,
    fill="#3485FF",
    outline="")

canvas.create_text(
    20.0,
    10.0,
    anchor="nw",
    text="CHAMPIONNAT",
    fill="#FFFFFF",
    font=("DelaGothicOne Regular", 21 * -1)
)

canvas.create_rectangle(
    16.0,
    46.0,
    147.0,
    50.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=596.0,
    y=590.0,
    width=250.0,
    height=35.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=53.0,
    y=590.0,
    width=250.0,
    height=35.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=325.0,
    y=590.0,
    width=250.0,
    height=35.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    362.0,
    204.0,
    image=image_image_1
)

canvas.create_rectangle(
    340.0,
    126.0,
    391.0,
    176.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    310.0,
    184.0,
    anchor="nw",
    text="CLUB 1",
    fill="#000000",
    font=("DelaGothicOne Regular", 12 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    537.0,
    204.0,
    image=image_image_2
)

canvas.create_text(
    479.0,
    184.0,
    anchor="nw",
    text="CLUB 2",
    fill="#000000",
    font=("DelaGothicOne Regular", 12 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=303.0,
    y=234.0,
    width=120.0,
    height=25.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=303.0,
    y=264.0,
    width=120.0,
    height=25.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=478.0,
    y=234.0,
    width=120.0,
    height=25.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=478.0,
    y=264.0,
    width=120.0,
    height=25.0
)

canvas.create_rectangle(
    511.0,
    120.0,
    558.0,
    178.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    472.0,
    210.0,
    anchor="nw",
    text="SCORE EXTERIEUR",
    fill="#C33232",
    font=("DelaGothicOne Regular", 8 * -1)
)

canvas.create_text(
    303.0,
    210.0,
    anchor="nw",
    text="SCORE DOMICILE",
    fill="#C33232",
    font=("DelaGothicOne Regular", 8 * -1)
)

canvas.create_text(
    433.0,
    185.0,
    anchor="nw",
    text="VS",
    fill="#FFFFFF",
    font=("DelaGothicOne Regular", 12 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    362.0,
    424.0,
    image=image_image_3
)

canvas.create_rectangle(
    340.0,
    346.0,
    391.0,
    396.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    310.0,
    404.0,
    anchor="nw",
    text="CLUB 1",
    fill="#000000",
    font=("DelaGothicOne Regular", 12 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    537.0,
    424.0,
    image=image_image_4
)

canvas.create_text(
    479.0,
    404.0,
    anchor="nw",
    text="CLUB 2",
    fill="#000000",
    font=("DelaGothicOne Regular", 12 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=303.0,
    y=454.0,
    width=120.0,
    height=25.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=303.0,
    y=484.0,
    width=120.0,
    height=25.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=478.0,
    y=454.0,
    width=120.0,
    height=25.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=478.0,
    y=484.0,
    width=120.0,
    height=25.0
)

canvas.create_rectangle(
    511.0,
    340.0,
    558.0,
    398.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    472.0,
    430.0,
    anchor="nw",
    text="SCORE EXTERIEUR",
    fill="#C33232",
    font=("DelaGothicOne Regular", 8 * -1)
)

canvas.create_text(
    303.0,
    430.0,
    anchor="nw",
    text="SCORE DOMICILE",
    fill="#C33232",
    font=("DelaGothicOne Regular", 8 * -1)
)

canvas.create_text(
    433.0,
    405.0,
    anchor="nw",
    text="VS",
    fill="#FFFFFF",
    font=("DelaGothicOne Regular", 12 * -1)
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=596.0,
    y=17.0,
    width=250.0,
    height=35.0
)
window.resizable(False, False)
window.mainloop()
